---
language: node_js
node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false
dist: trusty

cache:
  yarn: true

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn test

deploy:
  provider: npm
  email: kiwiupover@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
