---
language: node_js
node_js:
  - 'stable'
  - '7'
  - '6'
  - '5'
  - '4'

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - npm test
